const questionTypes = [
  {
    id: 'trivia',
    name: 'Trivia',
  },
  {
    id: 'cities',
    name: 'Cities of the World',
  },
  {
    id: 'landmarks',
    name: 'Landmarks',
  },
];

const questions = [
  {
    id: 0,
    question: 'Where is the Leaning Tower of Pisa?',
    mapType: 'street',
    type: 'landmarks',
    answers: [
      {
        type: 'exact',
        lat: 43.7230,
        lng: 10.3966,
      },
    ],
  },
  {
    id: 1,
    question: 'Where was The Titanic\'s wreckage found?',
    mapType: 'sat',
    type: 'trivia',
    answers: [
      {
        type: 'exact',
        lat: 41.726931,
        lng: -49.948253,
      },
    ],
  },
  {
    id: 2,
    question: 'Where is Machu Picchu?',
    mapType: 'sat',
    type: 'landmarks',
    answers: [
      {
        type: 'exact',
        lat: -13.1631,
        lng: -72.5450,
      },
    ],
  },
  {
    id: 3,
    question: 'Where would you have found Checkpoint Charlie?',
    mapType: 'sat',
    type: 'trivia',
    answers: [
      {
        type: 'exact',
        lat: 52.5074,
        lng: 13.3904,
      },
    ],
  },
  {
    id: 4,
    question: 'Where was the Battle of Hastings fought?',
    mapType: 'street',
    type: 'trivia',
    answers: [
      {
        type: 'exact',
        lat: 50.9072,
        lng: 0.4858,
      },
    ],
  },
  {
    id: 4,
    question: 'Where was the Battle of Gettysburg fought?',
    mapType: 'sat',
    type: 'trivia',
    answers: [
      {
        type: 'exact',
        lat: 39.8180,
        lng: -77.2325,
      },
    ],
  },
  {
    id: 5,
    question: 'Where is Mount Kilimanjaro?',
    mapType: 'sat',
    type: 'landmarks',
    answers: [
      {
        type: 'exact',
        lat: -3.0674,
        lng: 37.3556,
      },
    ],
  },
  {
    id: 6,
    question: 'Where is John F. Kennedy buried?',
    mapType: 'sat',
    type: 'trivia',
    answers: [
      {
        type: 'exact',
        lat: 38.8815,
        lng: -77.0715,
      },
    ],
  },
  {
    id: 7,
    question: 'Where is Easter Island?',
    mapType: 'sat',
    type: 'trivia',
    answers: [
      {
        type: 'exact',
        lat: -27.1127,
        lng: -109.3497,
      },
    ],
  },
  {
    id: 11,
    question: 'Where is Tokyo?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 35.685, lng: 139.7514 }],
  },
  {
    id: 12,
    question: 'Where is New York?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 40.6943, lng: -73.9249 }],
  },
  {
    id: 13,
    question: 'Where is Mexico City?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 19.4424, lng: -99.131 }],
  },
  {
    id: 14,
    question: 'Where is Mumbai?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 19.017, lng: 72.857 }],
  },
  {
    id: 15,
    question: 'Where is Sao Paulo?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -23.5587, lng: -46.625 }],
  },
  {
    id: 16,
    question: 'Where is Delhi?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 28.67, lng: 77.23 }],
  },
  {
    id: 17,
    question: 'Where is Shanghai?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 31.2165, lng: 121.4365 }],
  },
  {
    id: 18,
    question: 'Where is Kolkata?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 22.495, lng: 88.3247 }],
  },
  {
    id: 19,
    question: 'Where is Los Angeles?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 34.1139, lng: -118.4068 }],
  },
  {
    id: 20,
    question: 'Where is Dhaka?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 23.7231, lng: 90.4086 }],
  },
  {
    id: 21,
    question: 'Where is Buenos Aires?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -34.6025, lng: -58.3975 }],
  },
  {
    id: 22,
    question: 'Where is Karachi?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 24.87, lng: 66.99 }],
  },
  {
    id: 23,
    question: 'Where is Cairo?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 30.05, lng: 31.25 }],
  },
  {
    id: 24,
    question: 'Where is Rio de Janeiro?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -22.925, lng: -43.225 }],
  },
  {
    id: 25,
    question: 'Where is Osaka?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 34.75, lng: 135.4601 }],
  },
  {
    id: 26,
    question: 'Where is Beijing?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 39.9289, lng: 116.3883 }],
  },
  {
    id: 27,
    question: 'Where is Manila?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 14.6042, lng: 120.9822 }],
  },
  {
    id: 28,
    question: 'Where is Moscow?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 55.7522, lng: 37.6155 }],
  },
  {
    id: 29,
    question: 'Where is Istanbul?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 41.105, lng: 29.01 }],
  },
  {
    id: 30,
    question: 'Where is Paris?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 48.8667, lng: 2.3333 }],
  },
  {
    id: 31,
    question: 'Where is Seoul?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 37.5663, lng: 126.9997 }],
  },
  {
    id: 32,
    question: 'Where is Lagos?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 6.4433, lng: 3.3915 }],
  },
  {
    id: 33,
    question: 'Where is Jakarta?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -6.1744, lng: 106.8294 }],
  },
  {
    id: 34,
    question: 'Where is Guangzhou?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 23.145, lng: 113.325 }],
  },
  {
    id: 35,
    question: 'Where is Chicago?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 41.8373, lng: -87.6862 }],
  },
  {
    id: 36,
    question: 'Where is London?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 51.5, lng: -0.1167 }],
  },
  {
    id: 37,
    question: 'Where is Lima?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -12.048, lng: -77.0501 }],
  },
  {
    id: 38,
    question: 'Where is Tehran?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 35.6719, lng: 51.4243 }],
  },
  {
    id: 39,
    question: 'Where is Kinshasa?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -4.3297, lng: 15.315 }],
  },
  {
    id: 40,
    question: 'Where is Bogota?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 4.5964, lng: -74.0833 }],
  },
  {
    id: 41,
    question: 'Where is Shenzhen?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 22.5524, lng: 114.1221 }],
  },
  {
    id: 42,
    question: 'Where is Wuhan?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 30.58, lng: 114.27 }],
  },
  {
    id: 43,
    question: 'Where is Hong Kong?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 22.305, lng: 114.185 }],
  },
  {
    id: 44,
    question: 'Where is Tianjin?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 39.13, lng: 117.2 }],
  },
  {
    id: 45,
    question: 'Where is Chennai?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 13.09, lng: 80.28 }],
  },
  {
    id: 46,
    question: 'Where is Taipei?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 25.0358, lng: 121.5683 }],
  },
  {
    id: 47,
    question: 'Where is Bengaluru?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 12.97, lng: 77.56 }],
  },
  {
    id: 48,
    question: 'Where is Bangkok?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 13.75, lng: 100.5166 }],
  },
  {
    id: 49,
    question: 'Where is Lahore?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 31.56, lng: 74.35 }],
  },
  {
    id: 50,
    question: 'Where is Chongqing?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 29.565, lng: 106.595 }],
  },
  {
    id: 51,
    question: 'Where is Miami?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 25.7839, lng: -80.2102 }],
  },
  {
    id: 52,
    question: 'Where is Hyderabad?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 17.4, lng: 78.48 }],
  },
  {
    id: 53,
    question: 'Where is Dallas?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 32.7936, lng: -96.7662 }],
  },
  {
    id: 54,
    question: 'Where is Santiago?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -33.45, lng: -70.667 }],
  },
  {
    id: 55,
    question: 'Where is Philadelphia?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 40.0077, lng: -75.1339 }],
  },
  {
    id: 56,
    question: 'Where is Belo Horizonte?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -19.915, lng: -43.915 }],
  },
  {
    id: 57,
    question: 'Where is Madrid?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 40.4, lng: -3.6834 }],
  },
  {
    id: 58,
    question: 'Where is Houston?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 29.7869, lng: -95.3905 }],
  },
  {
    id: 59,
    question: 'Where is Ahmadabad?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 23.0301, lng: 72.58 }],
  },
  {
    id: 60,
    question: 'Where is Ho Chi Minh City?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 10.78, lng: 106.695 }],
  },
  {
    id: 61,
    question: 'Where is Washington?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 38.9047, lng: -77.0163 }],
  },
  {
    id: 62,
    question: 'Where is Atlanta?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 33.7627, lng: -84.4225 }],
  },
  {
    id: 63,
    question: 'Where is Toronto?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 43.7, lng: -79.42 }],
  },
  {
    id: 64,
    question: 'Where is Singapore?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 1.293, lng: 103.8558 }],
  },
  {
    id: 65,
    question: 'Where is Luanda?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -8.8383, lng: 13.2344 }],
  },
  {
    id: 66,
    question: 'Where is Baghdad?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 33.3386, lng: 44.3939 }],
  },
  {
    id: 67,
    question: 'Where is Barcelona?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 41.3833, lng: 2.1834 }],
  },
  {
    id: 68,
    question: 'Where is Haora?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 22.5804, lng: 88.3299 }],
  },
  {
    id: 69,
    question: 'Where is Shenyang?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 41.805, lng: 123.45 }],
  },
  {
    id: 70,
    question: 'Where is Khartoum?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 15.5881, lng: 32.5342 }],
  },
  {
    id: 71,
    question: 'Where is Pune?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 18.53, lng: 73.85 }],
  },
  {
    id: 72,
    question: 'Where is Boston?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 42.3188, lng: -71.0846 }],
  },
  {
    id: 73,
    question: 'Where is Sydney?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -33.92, lng: 151.1852 }],
  },
  {
    id: 74,
    question: 'Where is Saint Petersburg?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 59.939, lng: 30.316 }],
  },
  {
    id: 75,
    question: 'Where is Chittagong?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 22.33, lng: 91.8 }],
  },
  {
    id: 76,
    question: 'Where is Dongguan?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 23.0489, lng: 113.7447 }],
  },
  {
    id: 77,
    question: 'Where is Riyadh?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 24.6408, lng: 46.7727 }],
  },
  {
    id: 78,
    question: 'Where is Hanoi?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 21.0333, lng: 105.85 }],
  },
  {
    id: 79,
    question: 'Where is Guadalajara?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 20.67, lng: -103.33 }],
  },
  {
    id: 80,
    question: 'Where is Melbourne?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -37.82, lng: 144.975 }],
  },
  {
    id: 81,
    question: 'Where is Alexandria?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 31.2, lng: 29.95 }],
  },
  {
    id: 82,
    question: 'Where is Chengdu?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 30.67, lng: 104.07 }],
  },
  {
    id: 83,
    question: 'Where is Rangoon?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 16.7834, lng: 96.1667 }],
  },
  {
    id: 84,
    question: 'Where is Phoenix?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 33.5722, lng: -112.0891 }],
  },
  {
    id: 85,
    question: "Where is Xi'an?",
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 34.275, lng: 108.895 }],
  },
  {
    id: 86,
    question: 'Where is Porto Alegre?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -30.05, lng: -51.2 }],
  },
  {
    id: 87,
    question: 'Where is Surat?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 21.2, lng: 72.84 }],
  },
  {
    id: 88,
    question: 'Where is Hechi?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 23.0965, lng: 109.6091 }],
  },
  {
    id: 89,
    question: 'Where is Abidjan?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 5.32, lng: -4.04 }],
  },
  {
    id: 90,
    question: 'Where is Brasilia?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -15.7833, lng: -47.9161 }],
  },
  {
    id: 91,
    question: 'Where is Ankara?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 39.9272, lng: 32.8644 }],
  },
  {
    id: 92,
    question: 'Where is Monterrey?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 25.67, lng: -100.33 }],
  },
  {
    id: 93,
    question: 'Where is Yokohama?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 35.32, lng: 139.58 }],
  },
  {
    id: 94,
    question: 'Where is Nanjing?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 32.05, lng: 118.78 }],
  },
  {
    id: 95,
    question: 'Where is Montreal?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 45.5, lng: -73.5833 }],
  },
  {
    id: 96,
    question: 'Where is Guiyang?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 26.58, lng: 106.72 }],
  },
  {
    id: 97,
    question: 'Where is Recife?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -8.0756, lng: -34.9156 }],
  },
  {
    id: 98,
    question: 'Where is Seattle?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 47.6211, lng: -122.3244 }],
  },
  {
    id: 99,
    question: 'Where is Harbin?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 45.75, lng: 126.65 }],
  },
  {
    id: 100,
    question: 'Where is San Francisco?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 37.7562, lng: -122.443 }],
  },
  {
    id: 101,
    question: 'Where is Fortaleza?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -3.75, lng: -38.58 }],
  },
  {
    id: 102,
    question: 'Where is Zhangzhou?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 24.5204, lng: 117.67 }],
  },
  {
    id: 103,
    question: 'Where is Detroit?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 42.3834, lng: -83.1024 }],
  },
  {
    id: 104,
    question: 'Where is Salvador?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -12.97, lng: -38.48 }],
  },
  {
    id: 105,
    question: 'Where is Busan?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 35.0951, lng: 129.01 }],
  },
  {
    id: 106,
    question: 'Where is Johannesburg?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -26.17, lng: 28.03 }],
  },
  {
    id: 107,
    question: 'Where is Berlin?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 52.5218, lng: 13.4015 }],
  },
  {
    id: 108,
    question: 'Where is Algiers?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 36.7631, lng: 3.0506 }],
  },
  {
    id: 109,
    question: 'Where is Rome?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 41.896, lng: 12.4833 }],
  },
  {
    id: 110,
    question: 'Where is Pyongyang?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 39.0194, lng: 125.7547 }],
  },
  {
    id: 111,
    question: 'Where is Medellin?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 6.275, lng: -75.575 }],
  },
  {
    id: 112,
    question: 'Where is Kabul?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 34.5167, lng: 69.1833 }],
  },
  {
    id: 113,
    question: 'Where is Athens?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 37.9833, lng: 23.7333 }],
  },
  {
    id: 114,
    question: 'Where is Nagoya?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 35.155, lng: 136.915 }],
  },
  {
    id: 115,
    question: 'Where is Cape Town?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -33.92, lng: 18.435 }],
  },
  {
    id: 116,
    question: 'Where is San Diego?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 32.8312, lng: -117.1225 }],
  },
  {
    id: 117,
    question: 'Where is Changchun?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 43.865, lng: 125.34 }],
  },
  {
    id: 118,
    question: 'Where is Casablanca?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 33.6, lng: -7.6164 }],
  },
  {
    id: 119,
    question: 'Where is Dalian?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 38.9228, lng: 121.6298 }],
  },
  {
    id: 120,
    question: 'Where is Cawnpore?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 26.46, lng: 80.32 }],
  },
  {
    id: 121,
    question: 'Where is Kano?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 12, lng: 8.52 }],
  },
  {
    id: 122,
    question: 'Where is Tel Aviv-Yafo?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 32.08, lng: 34.77 }],
  },
  {
    id: 123,
    question: 'Where is Addis Ababa?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 9.0333, lng: 38.7 }],
  },
  {
    id: 124,
    question: 'Where is Curitiba?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -25.42, lng: -49.32 }],
  },
  {
    id: 125,
    question: 'Where is Zibo?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 36.8, lng: 118.05 }],
  },
  {
    id: 126,
    question: 'Where is Jeddah?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 21.5169, lng: 39.2192 }],
  },
  {
    id: 127,
    question: 'Where is Nairobi?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -1.2833, lng: 36.8167 }],
  },
  {
    id: 128,
    question: 'Where is Hangzhou?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 30.25, lng: 120.17 }],
  },
  {
    id: 129,
    question: 'Where is Benoni?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -26.1496, lng: 28.3299 }],
  },
  {
    id: 130,
    question: 'Where is Caracas?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 10.501, lng: -66.917 }],
  },
  {
    id: 131,
    question: 'Where is Milan?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 45.47, lng: 9.205 }],
  },
  {
    id: 132,
    question: 'Where is Stuttgart?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 48.78, lng: 9.2 }],
  },
  {
    id: 133,
    question: 'Where is Kunming?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 25.07, lng: 102.68 }],
  },
  {
    id: 134,
    question: 'Where is Dar es Salaam?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -6.8, lng: 39.2683 }],
  },
  {
    id: 135,
    question: 'Where is Minneapolis?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 44.9635, lng: -93.2678 }],
  },
  {
    id: 136,
    question: 'Where is Jaipur?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 26.9211, lng: 75.81 }],
  },
  {
    id: 137,
    question: 'Where is Taiyuan?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 37.875, lng: 112.5451 }],
  },
  {
    id: 138,
    question: 'Where is Frankfurt?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 50.1, lng: 8.675 }],
  },
  {
    id: 139,
    question: 'Where is Qingdao?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 36.09, lng: 120.33 }],
  },
  {
    id: 140,
    question: 'Where is Surabaya?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -7.2492, lng: 112.7508 }],
  },
  {
    id: 141,
    question: 'Where is Lisbon?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 38.7227, lng: -9.1449 }],
  },
  {
    id: 142,
    question: 'Where is Tampa?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 27.9942, lng: -82.4451 }],
  },
  {
    id: 143,
    question: 'Where is Jinan?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 36.675, lng: 116.995 }],
  },
  {
    id: 144,
    question: 'Where is Fukuoka?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 33.595, lng: 130.41 }],
  },
  {
    id: 145,
    question: 'Where is Campinas?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -22.9, lng: -47.1 }],
  },
  {
    id: 146,
    question: 'Where is Denver?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 39.7621, lng: -104.8759 }],
  },
  {
    id: 147,
    question: 'Where is Kaohsiung?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 22.6333, lng: 120.2666 }],
  },
  {
    id: 148,
    question: 'Where is Quezon City?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 14.6504, lng: 121.03 }],
  },
  {
    id: 149,
    question: 'Where is Katowice?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 50.2604, lng: 19.02 }],
  },
  {
    id: 150,
    question: 'Where is Aleppo?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 36.23, lng: 37.17 }],
  },
  {
    id: 151,
    question: 'Where is Durban?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -29.865, lng: 30.98 }],
  },
  {
    id: 152,
    question: 'Where is Kyiv?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 50.4334, lng: 30.5166 }],
  },
  {
    id: 153,
    question: 'Where is Lucknow?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 26.855, lng: 80.915 }],
  },
  {
    id: 154,
    question: 'Where is Giza?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 30.01, lng: 31.19 }],
  },
  {
    id: 155,
    question: 'Where is Zhengzhou?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 34.755, lng: 113.6651 }],
  },
  {
    id: 156,
    question: 'Where is Taichung?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 24.1521, lng: 120.6817 }],
  },
  {
    id: 157,
    question: 'Where is Brooklyn?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 40.6501, lng: -73.9496 }],
  },
  {
    id: 158,
    question: 'Where is Ibadan?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 7.38, lng: 3.93 }],
  },
  {
    id: 159,
    question: 'Where is Faisalabad?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 31.41, lng: 73.11 }],
  },
  {
    id: 160,
    question: 'Where is Fuzhou?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 26.08, lng: 119.3 }],
  },
  {
    id: 161,
    question: 'Where is Changsha?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 28.2, lng: 112.97 }],
  },
  {
    id: 162,
    question: 'Where is Dakar?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 14.7158, lng: -17.4731 }],
  },
  {
    id: 163,
    question: 'Where is Izmir?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 38.4361, lng: 27.1518 }],
  },
  {
    id: 164,
    question: 'Where is Xiangtan?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 27.8504, lng: 112.9 }],
  },
  {
    id: 165,
    question: 'Where is Lanzhou?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 36.056, lng: 103.792 }],
  },
  {
    id: 166,
    question: 'Where is Incheon?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 37.4761, lng: 126.6422 }],
  },
  {
    id: 167,
    question: 'Where is Sapporo?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 43.075, lng: 141.34 }],
  },
  {
    id: 168,
    question: 'Where is Xiamen?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 24.45, lng: 118.08 }],
  },
  {
    id: 169,
    question: 'Where is Guayaquil?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -2.22, lng: -79.92 }],
  },
  {
    id: 170,
    question: 'Where is George Town?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 5.4136, lng: 100.3294 }],
  },
  {
    id: 171,
    question: 'Where is Mashhad?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 36.27, lng: 59.57 }],
  },
  {
    id: 172,
    question: 'Where is Damascus?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 33.5, lng: 36.3 }],
  },
  {
    id: 173,
    question: 'Where is Daegu?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 35.8668, lng: 128.607 }],
  },
  {
    id: 174,
    question: 'Where is Nagpur?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 21.17, lng: 79.09 }],
  },
  {
    id: 175,
    question: 'Where is Lianshan?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 40.7503, lng: 120.83 }],
  },
  {
    id: 176,
    question: 'Where is Shijiazhuang?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 38.05, lng: 114.48 }],
  },
  {
    id: 177,
    question: 'Where is Tunis?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 36.8028, lng: 10.1797 }],
  },
  {
    id: 178,
    question: 'Where is Vienna?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 48.2, lng: 16.3666 }],
  },
  {
    id: 179,
    question: 'Where is Jilin?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 43.85, lng: 126.55 }],
  },
  {
    id: 180,
    question: 'Where is Omdurman?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 15.6167, lng: 32.48 }],
  },
  {
    id: 181,
    question: 'Where is Bandung?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -6.95, lng: 107.57 }],
  },
  {
    id: 182,
    question: 'Where is Bekasi?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -6.2173, lng: 106.9723 }],
  },
  {
    id: 183,
    question: 'Where is Mannheim?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 49.5004, lng: 8.47 }],
  },
  {
    id: 184,
    question: 'Where is Nanchang?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 28.68, lng: 115.88 }],
  },
  {
    id: 185,
    question: 'Where is Wenzhou?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 28.02, lng: 120.6501 }],
  },
  {
    id: 186,
    question: 'Where is Queens?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 40.7498, lng: -73.7976 }],
  },
  {
    id: 187,
    question: 'Where is Vancouver?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 49.2734, lng: -123.1216 }],
  },
  {
    id: 188,
    question: 'Where is Birmingham?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 52.475, lng: -1.92 }],
  },
  {
    id: 189,
    question: 'Where is Cali?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 3.4, lng: -76.5 }],
  },
  {
    id: 190,
    question: 'Where is Naples?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 40.84, lng: 14.245 }],
  },
  {
    id: 191,
    question: 'Where is Sendai?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 38.2871, lng: 141.0217 }],
  },
  {
    id: 192,
    question: 'Where is Manchester?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 53.5004, lng: -2.248 }],
  },
  {
    id: 193,
    question: 'Where is Puebla?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 19.05, lng: -98.2 }],
  },
  {
    id: 194,
    question: 'Where is Tripoli?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 32.8925, lng: 13.18 }],
  },
  {
    id: 195,
    question: 'Where is Tashkent?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 41.3117, lng: 69.2949 }],
  },
  {
    id: 196,
    question: 'Where is Havana?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 23.132, lng: -82.3642 }],
  },
  {
    id: 197,
    question: 'Where is Gaoping?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 30.7804, lng: 106.13 }],
  },
  {
    id: 198,
    question: 'Where is Baltimore?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 39.3051, lng: -76.6144 }],
  },
  {
    id: 199,
    question: 'Where is Nanning?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 22.82, lng: 108.32 }],
  },
  {
    id: 200,
    question: 'Where is Belem?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -1.45, lng: -48.48 }],
  },
  {
    id: 201,
    question: 'Where is Patna?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 25.625, lng: 85.13 }],
  },
  {
    id: 202,
    question: 'Where is Santo Domingo?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 18.4701, lng: -69.9001 }],
  },
  {
    id: 203,
    question: 'Where is Urumqi?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 43.805, lng: 87.575 }],
  },
  {
    id: 204,
    question: 'Where is Zaozhuang?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 34.88, lng: 117.57 }],
  },
  {
    id: 205,
    question: 'Where is Baku?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 40.3953, lng: 49.8622 }],
  },
  {
    id: 206,
    question: 'Where is Accra?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 5.55, lng: -0.2167 }],
  },
  {
    id: 207,
    question: 'Where is Yantai?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 37.5304, lng: 121.4 }],
  },
  {
    id: 208,
    question: 'Where is Medan?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 3.58, lng: 98.65 }],
  },
  {
    id: 209,
    question: 'Where is Santa Cruz?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -17.7539, lng: -63.226 }],
  },
  {
    id: 210,
    question: 'Where is Tongshan?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 34.28, lng: 117.18 }],
  },
  {
    id: 211,
    question: 'Where is Riverside?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 33.9381, lng: -117.3948 }],
  },
  {
    id: 212,
    question: 'Where is Linyi?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 35.08, lng: 118.33 }],
  },
  {
    id: 213,
    question: 'Where is St. Louis?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 38.6358, lng: -90.2451 }],
  },
  {
    id: 214,
    question: 'Where is Las Vegas?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 36.2333, lng: -115.2654 }],
  },
  {
    id: 215,
    question: 'Where is Maracaibo?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 10.73, lng: -71.66 }],
  },
  {
    id: 216,
    question: 'Where is Kuwait City?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 29.3697, lng: 47.9783 }],
  },
  {
    id: 217,
    question: 'Where is Ad Dammam?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 26.4282, lng: 50.0997 }],
  },
  {
    id: 218,
    question: 'Where is Portland?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 45.5371, lng: -122.65 }],
  },
  {
    id: 219,
    question: 'Where is Haikou?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 20.05, lng: 110.32 }],
  },
  {
    id: 220,
    question: 'Where is Hiroshima?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 34.3878, lng: 132.4429 }],
  },
  {
    id: 221,
    question: 'Where is Baotou?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 40.6522, lng: 109.822 }],
  },
  {
    id: 222,
    question: 'Where is Hefei?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 31.85, lng: 117.28 }],
  },
  {
    id: 223,
    question: 'Where is Indore?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 22.7151, lng: 75.865 }],
  },
  {
    id: 224,
    question: 'Where is Goiania?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -16.72, lng: -49.3 }],
  },
  {
    id: 225,
    question: 'Where is Sanaa?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 15.3547, lng: 44.2066 }],
  },
  {
    id: 226,
    question: 'Where is San Antonio?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 29.4658, lng: -98.5254 }],
  },
  {
    id: 227,
    question: 'Where is Port-au-Prince?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 18.541, lng: -72.336 }],
  },
  {
    id: 228,
    question: 'Where is Haiphong?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 20.83, lng: 106.6801 }],
  },
  {
    id: 229,
    question: 'Where is Suzhou?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 33.6361, lng: 116.9789 }],
  },
  {
    id: 230,
    question: 'Where is Nanyang?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 33.0004, lng: 112.53 }],
  },
  {
    id: 231,
    question: 'Where is Bucharest?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 44.4334, lng: 26.0999 }],
  },
  {
    id: 232,
    question: 'Where is Ningbo?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 29.88, lng: 121.55 }],
  },
  {
    id: 233,
    question: 'Where is Douala?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 4.0604, lng: 9.71 }],
  },
  {
    id: 234,
    question: 'Where is Tangshan?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 39.6243, lng: 118.1944 }],
  },
  {
    id: 235,
    question: 'Where is Tainan?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 23, lng: 120.2 }],
  },
  {
    id: 236,
    question: 'Where is Xiping?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 40.08, lng: 113.3 }],
  },
  {
    id: 237,
    question: 'Where is Asuncion?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -25.2964, lng: -57.6415 }],
  },
  {
    id: 238,
    question: 'Where is Saidu Sharif?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 34.75, lng: 72.35 }],
  },
  {
    id: 239,
    question: 'Where is Brisbane?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -27.455, lng: 153.0351 }],
  },
  {
    id: 240,
    question: 'Where is Rawalpindi?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 33.6, lng: 73.04 }],
  },
  {
    id: 241,
    question: 'Where is Sacramento?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 38.5667, lng: -121.4683 }],
  },
  {
    id: 242,
    question: 'Where is Beirut?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 33.872, lng: 35.5097 }],
  },
  {
    id: 243,
    question: 'Where is San Jose?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 37.3021, lng: -121.8489 }],
  },
  {
    id: 244,
    question: 'Where is Minsk?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 53.9, lng: 27.5666 }],
  },
  {
    id: 245,
    question: 'Where is Kyoto?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 35.03, lng: 135.75 }],
  },
  {
    id: 246,
    question: 'Where is Barranquilla?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 10.96, lng: -74.8 }],
  },
  {
    id: 247,
    question: 'Where is Orlando?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 28.4772, lng: -81.3369 }],
  },
  {
    id: 248,
    question: 'Where is Shuyangzha?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 34.1299, lng: 118.7734 }],
  },
  {
    id: 249,
    question: 'Where is Valencia?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 10.23, lng: -67.98 }],
  },
  {
    id: 250,
    question: 'Where is Hamburg?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 53.55, lng: 10 }],
  },
  {
    id: 251,
    question: 'Where is Vadodara?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 22.31, lng: 73.18 }],
  },
  {
    id: 252,
    question: 'Where is Manaus?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -3.1, lng: -60 }],
  },
  {
    id: 253,
    question: 'Where is Shangqiu?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 34.4504, lng: 115.65 }],
  },
  {
    id: 254,
    question: 'Where is Wuxi?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 31.58, lng: 120.3 }],
  },
  {
    id: 255,
    question: 'Where is Palembang?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: -2.98, lng: 104.75 }],
  },
  {
    id: 256,
    question: 'Where is Brussels?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 50.8333, lng: 4.3333 }],
  },
  {
    id: 257,
    question: 'Where is Essen?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 51.45, lng: 7.0166 }],
  },
  {
    id: 258,
    question: 'Where is Cleveland?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 41.4767, lng: -81.6805 }],
  },
  {
    id: 259,
    question: 'Where is Bhopal?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 23.25, lng: 77.41 }],
  },
  {
    id: 260,
    question: 'Where is Hohhot?',
    mapType: 'sat',
    type: 'cities',
    answers: [{ type: 'exact', lat: 40.82, lng: 111.66 }],
  },
  
];
